github:
  - name: BIPs
    domain: https://github.com/bitcoin/bips
    url: https://github.com/bitcoin/bips.git
  - name: BOLTs
    domain: https://github.com/lightning/bolts
    url: https://github.com/lightning/bolts.git
  - name: BLIPs
    domain: https://github.com/lightning/blips
    url: https://github.com/lightning/blips.git
  - name: BitcoinOps
    domain: https://bitcoinops.org
    url: https://github.com/bitcoinops/bitcoinops.github.io.git
    directories: 
      _posts/en: post
      _topics/en: topic
  - name: BitcoinTranscripts
    domain: https://btctranscripts.com
    url: https://github.com/bitcointranscripts/bitcointranscripts.git
    processors:
      - summarization
      - topic_extractor
      - vector_embeddings
  - name: PR-Review-Club
    domain: https://bitcoincore.reviews/
    url: https://github.com/bitcoin-core-review-club/website.git
    directories: 
      _posts: post
web:
  - name: BitcoinTalk
    domain: https://bitcointalk.org
    url: https://bitcointalk.org/index.php?board=6.0
    analyzer_config:
      index_url: https://bitcointalk.org/index.php?board=6.0
      resource_url: https://bitcointalk.org/index.php?topic=5499150.0
  - name: StackExchange
    domain: https://bitcoin.stackexchange.com
    url: https://api.stackexchange.com
