name: AI Scraper
on:
#  schedule:
#    - cron: '35 12 * * *' # every day at midnight
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: write

jobs:
  execute_and_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai_scraper/requirements2.txt
          playwright install

      - name: Execute Python script
        run: |
          mkdir /tmp/ai_scraper
          python ai_scraper/main.py

        env:
            DATA_DIR: /tmp/ai_scraper
            ES_ENGINE: ${{ secrets.ES_ENGINE }}
            ES_URL: ${{ secrets.ES_URL }}
            ES_TOKEN: ${{ secrets.ES_TOKEN }}
            CLOUD_ID: ${{ secrets.CLOUD_ID }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
            USERNAME: ${{ secrets.USERNAME }}
            INDEX: ${{ secrets.INDEX }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            SCRAPE_CONFIG_PATH: "ai_scraper/configs/general_config.json"
            MODEL_CONFIG_PATH: "ai_scraper/configs/model_config.json"

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
          git config user.name "${{ secrets.GIT_AUTHOR_NAME }}"

      - name: Add and commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated generated_scripts from AI Scraper"
            git push
          fi