name: New Bitcoin Mailing list
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch data
        run: |
          python mailing-list/main.py

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
          git config user.name "${{ secrets.GIT_AUTHOR_NAME }}"

      - name: Add and commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "updated scraper logs"
            git push
          fi

        env:
            ES_ENGINE: ${{ secrets.ES_ENGINE }}
            ES_URL: ${{ secrets.ES_URL }}
            ES_TOKEN: ${{ secrets.ES_TOKEN }}
            CLOUD_ID: ${{ secrets.CLOUD_ID }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
            USERNAME: ${{ secrets.USERNAME }}
            INDEX: ${{ secrets.INDEX }}
            DATA_DIR: /tmp/data
