name: StackExchange
on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
        DATA_DIR: /tmp/stackexchange
        ES_ENGINE: ${{ secrets.ES_ENGINE }}
        ES_URL: ${{ secrets.ES_URL }}
        ES_TOKEN: ${{ secrets.ES_TOKEN }}
        CLOUD_ID: ${{ secrets.CLOUD_ID }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}
        INDEX: ${{ secrets.INDEX }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch data
        run: |
          mkdir /tmp/stackexchange
          python bitcoin.stackexchange.com/main.py

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
          git config user.name "${{ secrets.GIT_AUTHOR_NAME }}"

      - name: Add and commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "stackexchange: updated scraper logs"
            git push
          fi
